-- Canonical schema source:
-- supabase/migrations/20260812163000_reset_and_create_anonymous_community.sql
--
-- Do not add DDL to this file. Apply and maintain schema changes as Supabase
-- migrations so the local history is the single source of truth.
