import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Brain,
  Cake,
  Calendar,
  Camera,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardList,
  Copy,
  Download,
  Eye,
  EyeOff,
  Folder,
  FolderOpen,
  Gift,
  Gamepad2,
  Heart,
  HelpCircle,
  Image as ImageIcon,
  Info,
  LoaderCircle,
  Mail,
  Maximize2,
  Menu,
  MessageCircle,
  Mic,
  Minimize2,
  Minus,
  Music,
  Pause,
  PartyPopper,
  PenLine,
  Play,
  Puzzle,
  Search,
  Send,
  Share2,
  SkipBack,
  SkipForward,
  StopCircle,
  Trophy,
  Upload,
  Users,
  Video,
  Volume1,
  Volume2,
  VolumeX,
  Wind,
  X,
  type LucideIcon,
} from 'lucide-react'

export const Icons = {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Brain,
  Cake,
  Calendar,
  Camera,
  CheckCircle: CheckCircle2,
  CheckCircle2,
  CircleAlert,
  CircleCheck,
  CircleX,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Close: X,
  Comment: MessageCircle,
  Copy,
  Download,
  Eye,
  EyeOff,
  Folder,
  FolderOpen,
  Gamepad: Gamepad2,
  Gift,
  Heart,
  HelpCircle,
  Image: ImageIcon,
  Info,
  LoaderCircle,
  Mail,
  Maximize2,
  Menu,
  MessageCircle,
  Mic,
  Minimize2,
  Minus,
  Music,
  Pause,
  Party: PartyPopper,
  PenLine,
  Play,
  Puzzle,
  Search,
  Send,
  Share2,
  SkipBack,
  SkipForward,
  StopCircle,
  Trophy,
  Upload,
  Users,
  Video,
  Volume: Volume2,
  Volume1,
  Volume2,
  VolumeX,
  Wind,
  X,
} as const

interface IconProps
  extends Pick<
    React.SVGProps<SVGSVGElement>,
    'aria-hidden' | 'aria-label' | 'aria-labelledby' | 'aria-describedby' | 'role' | 'tabIndex'
  > {
  name: keyof typeof Icons
  size?: number
  className?: string
  style?: React.CSSProperties
}

const iconToneClasses: Partial<Record<keyof typeof Icons, string>> = {
  AlertTriangle: 'text-amber-500',
  CircleAlert: 'text-amber-500',
  CircleCheck: 'text-emerald-500',
  CircleX: 'text-rose-500',
  CheckCircle: 'text-emerald-500',
  CheckCircle2: 'text-emerald-500',
  Heart: 'text-pink-500',
  Info: 'text-sky-500',
  Mail: 'text-pink-500',
  Party: 'text-amber-500',
  Gift: 'text-fuchsia-500',
  Camera: 'text-orange-500',
  Video: 'text-sky-500',
  Folder: 'text-violet-500',
  FolderOpen: 'text-violet-500',
  Image: 'text-cyan-500',
  Upload: 'text-sky-500',
  Download: 'text-sky-500',
  Play: 'text-emerald-500',
  Pause: 'text-amber-500',
  SkipBack: 'text-sky-500',
  SkipForward: 'text-sky-500',
  Volume: 'text-teal-500',
  Volume1: 'text-teal-500',
  Volume2: 'text-teal-500',
  VolumeX: 'text-rose-500',
  Close: 'text-rose-500',
  X: 'text-rose-500',
}

export function Icon({ name, size = 20, className, style, ...ariaProps }: IconProps) {
  const IconComponent = Icons[name] as LucideIcon
  const toneClass = iconToneClasses[name as keyof typeof iconToneClasses]
  const classes = [toneClass, className].filter(Boolean).join(' ')

  return (
    <IconComponent
      size={size}
      className={classes || undefined}
      style={style}
      aria-hidden={ariaProps['aria-hidden'] ?? true}
      {...ariaProps}
    />
  )
}
