begin;

create table if not exists public.time_capsules (
  id bigint generated always as identity primary key,
  sender text not null check (char_length(btrim(sender)) between 1 and 80),
  recipient text check (recipient is null or char_length(btrim(recipient)) between 1 and 80),
  message text not null check (char_length(btrim(message)) between 1 and 2000),
  photo_url text check (photo_url is null or char_length(photo_url) <= 1000),
  unlock_date date not null,
  created_at timestamptz not null default now(),
  owner_id uuid references auth.users(id) on delete set null,
  idempotency_key text check (idempotency_key is null or char_length(btrim(idempotency_key)) between 1 and 128),
  invite_token_hash text check (invite_token_hash is null or char_length(btrim(invite_token_hash)) between 1 and 128),
  invite_token_expires_at timestamptz,
  invite_revoked_at timestamptz,
  photo_object_path text check (photo_object_path is null or char_length(btrim(photo_object_path)) between 1 and 500)
);

create index if not exists time_capsules_unlock_date_idx on public.time_capsules (unlock_date asc);
create index if not exists time_capsules_created_at_idx on public.time_capsules (created_at desc);
create unique index if not exists time_capsules_owner_idempotency_key_uidx
  on public.time_capsules (owner_id, idempotency_key)
  where owner_id is not null and idempotency_key is not null;
create unique index if not exists time_capsules_invite_token_hash_uidx
  on public.time_capsules (invite_token_hash)
  where invite_token_hash is not null;
create index if not exists time_capsules_owner_unlock_date_idx
  on public.time_capsules (owner_id, unlock_date asc);
create index if not exists time_capsules_invite_token_expires_at_idx
  on public.time_capsules (invite_token_hash, invite_token_expires_at)
  where invite_token_hash is not null and invite_revoked_at is null;

alter table public.time_capsules enable row level security;
revoke all on public.time_capsules from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'time-capsules-private',
  'time-capsules-private',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.time_capsule_access_codes (
  id bigint generated by default as identity primary key,
  capsule_id bigint not null references public.time_capsules(id) on delete cascade,
  code_hash text not null unique,
  derivation_attempt integer not null default 0 check (derivation_attempt >= 0),
  revoked_at timestamptz,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists time_capsule_access_codes_capsule_id_idx
  on public.time_capsule_access_codes (capsule_id);

alter table public.time_capsule_access_codes enable row level security;
revoke all on public.time_capsule_access_codes from anon, authenticated;
grant select, insert, update on public.time_capsule_access_codes to service_role;
grant usage, select on sequence public.time_capsule_access_codes_id_seq to service_role;

create table if not exists public.time_capsule_access_attempt_buckets (
  bucket_fingerprint text primary key,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  updated_at timestamptz not null default now(),
  constraint time_capsule_access_attempt_buckets_fingerprint_check check (length(bucket_fingerprint) = 64),
  constraint time_capsule_access_attempt_buckets_failed_attempts_check check (failed_attempts >= 0)
);

alter table public.time_capsule_access_attempt_buckets enable row level security;
revoke all on public.time_capsule_access_attempt_buckets from anon, authenticated;
grant select, insert, update on public.time_capsule_access_attempt_buckets to service_role;

create or replace function public.create_time_capsule_with_access_code(
  input_owner_id uuid,
  input_idempotency_key text,
  input_sender text,
  input_recipient text,
  input_message text,
  input_unlock_date date,
  input_photo_object_path text,
  input_invite_token_hash text,
  input_invite_token_expires_at timestamptz,
  input_access_code_hashes text[]
)
returns table (capsule_id bigint, derivation_attempt integer, idempotent boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  capsule_row public.time_capsules%rowtype;
  attempt integer;
begin
  if coalesce(current_setting('request.jwt.claim.role', true), '') <> 'service_role' then
    raise exception 'service_role_required';
  end if;

  insert into public.time_capsules (
    owner_id, idempotency_key, sender, recipient, message, unlock_date,
    photo_object_path, invite_token_hash, invite_token_expires_at
  )
  values (
    input_owner_id, input_idempotency_key, input_sender, input_recipient,
    input_message, input_unlock_date, input_photo_object_path,
    input_invite_token_hash, input_invite_token_expires_at
  )
  on conflict (owner_id, idempotency_key)
    where owner_id is not null and idempotency_key is not null
    do nothing
  returning * into capsule_row;

  if not found then
    select * into capsule_row
    from public.time_capsules
    where owner_id = input_owner_id and idempotency_key = input_idempotency_key
    for update;

    if not found or capsule_row.invite_token_hash is distinct from input_invite_token_hash then
      raise exception 'idempotency_replay_unavailable';
    end if;

    select access.derivation_attempt into attempt
    from public.time_capsule_access_codes access
    where access.capsule_id = capsule_row.id
    order by access.id
    limit 1;

    if not found then
      raise exception 'idempotency_replay_unavailable';
    end if;

    return query select capsule_row.id, attempt, true;
    return;
  end if;

  for attempt in 1..coalesce(array_length(input_access_code_hashes, 1), 0) loop
    begin
      insert into public.time_capsule_access_codes (capsule_id, code_hash, derivation_attempt)
      values (capsule_row.id, input_access_code_hashes[attempt], attempt - 1);
      return query select capsule_row.id, attempt - 1, false;
      return;
    exception when unique_violation then
      null;
    end;
  end loop;

  raise exception 'access_code_collision_exhausted';
end;
$$;

revoke all on function public.create_time_capsule_with_access_code(uuid, text, text, text, text, date, text, text, timestamptz, text[]) from public, anon, authenticated;
grant execute on function public.create_time_capsule_with_access_code(uuid, text, text, text, text, date, text, text, timestamptz, text[]) to service_role;

drop function if exists public.consume_time_capsule_access_code(text);

create or replace function public.consume_time_capsule_access_code(
  input_code_hash text,
  input_attempt_bucket text
)
returns table (capsule_id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  access_row public.time_capsule_access_codes%rowtype;
  bucket_row public.time_capsule_access_attempt_buckets%rowtype;
begin
  if coalesce(current_setting('request.jwt.claim.role', true), '') <> 'service_role' then
    raise exception 'service_role_required';
  end if;

  insert into public.time_capsule_access_attempt_buckets (bucket_fingerprint)
  values (input_attempt_bucket)
  on conflict (bucket_fingerprint) do nothing;

  select * into bucket_row
  from public.time_capsule_access_attempt_buckets
  where bucket_fingerprint = input_attempt_bucket
  for update;

  if bucket_row.locked_until is not null and bucket_row.locked_until > now() then
    return;
  end if;

  if bucket_row.locked_until is not null and bucket_row.locked_until <= now() then
    update public.time_capsule_access_attempt_buckets
    set failed_attempts = 0, locked_until = null, updated_at = now()
    where bucket_fingerprint = input_attempt_bucket;
  end if;

  select ac.* into access_row
  from public.time_capsule_access_codes ac
  join public.time_capsules tc on tc.id = ac.capsule_id
  where ac.code_hash = input_code_hash
    and ac.revoked_at is null
    and (ac.locked_until is null or ac.locked_until <= now())
    and tc.invite_revoked_at is null
  for update;

  if not found then
    update public.time_capsule_access_attempt_buckets
    set failed_attempts = failed_attempts + 1,
        locked_until = case when failed_attempts + 1 >= 5 then now() + interval '15 minutes' else null end,
        updated_at = now()
    where bucket_fingerprint = input_attempt_bucket;
    return;
  end if;

  update public.time_capsule_access_attempt_buckets
  set failed_attempts = 0, locked_until = null, updated_at = now()
  where bucket_fingerprint = input_attempt_bucket;

  update public.time_capsule_access_codes
  set failed_attempts = 0, locked_until = null, last_used_at = now()
  where id = access_row.id;

  return query select access_row.capsule_id;
end;
$$;

revoke all on function public.consume_time_capsule_access_code(text, text) from public, anon, authenticated;
grant execute on function public.consume_time_capsule_access_code(text, text) to service_role;

commit;
