begin;

create table if not exists public.time_capsule_access_codes (
  id bigint generated by default as identity primary key,
  capsule_id bigint not null references public.time_capsules(id) on delete cascade,
  code_hash text not null,
  derivation_attempt integer not null default 0,
  revoked_at timestamptz,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  constraint time_capsule_access_codes_code_hash_key unique (code_hash),
  constraint time_capsule_access_codes_derivation_attempt_check check (derivation_attempt >= 0),
  constraint time_capsule_access_codes_failed_attempts_check check (failed_attempts >= 0)
);

create index if not exists time_capsule_access_codes_capsule_id_idx
  on public.time_capsule_access_codes (capsule_id);

alter table public.time_capsule_access_codes enable row level security;

revoke all on public.time_capsule_access_codes from anon, authenticated;
grant select, insert, update on public.time_capsule_access_codes to service_role;
grant usage, select on sequence public.time_capsule_access_codes_id_seq to service_role;

create or replace function public.consume_time_capsule_access_code(input_code_hash text)
returns table (capsule_id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  access_row public.time_capsule_access_codes%rowtype;
begin
  select * into access_row
  from public.time_capsule_access_codes
  where code_hash = input_code_hash
    and revoked_at is null
  for update;

  if not found then
    return;
  end if;

  if access_row.locked_until is not null and access_row.locked_until > now() then
    return;
  end if;

  update public.time_capsule_access_codes
  set failed_attempts = 0,
      locked_until = null,
      last_used_at = now()
  where id = access_row.id;

  return query select access_row.capsule_id;
end;
$$;

revoke all on function public.consume_time_capsule_access_code(text) from public;
grant execute on function public.consume_time_capsule_access_code(text) to service_role;

commit;
